config/routes.rb
Rails.application.routes.draw do
  resources :waypoints
  resources :routes do
  	match '/add_waypoints', :to => 'routes#add_waypoints', :via => :get, :as => :add_waypoints
  	match '/add_link/:waypoint_id', :to => 'routes#add_link', :via => :get, :as => :add_link
  end

  devise_for :users
  root 'welcome#index'
  get '/game/:level', :to => 'welcome#game', as: :welcome_game
  get '/levelSelect', :to => 'welcome#levelSelect', as: :welcome_select
  match "/guess_the_road_sign", :to => "guess_road_sign#index", :via => :get, :as => :grs_index
  match "/guess_the_road_sign/start", :to => "guess_road_sign#start", :via => :get, :as => :grs_start
  match "/guess_the_road_sign/:page", :to => "guess_road_sign#page", :via => :get, :as => :grs_page
  post "/guess_the_road_sign/:page/check", :to => "guess_road_sign#check", as: :grs_check

  resources :road_sign
  resources :levels do
    match '/set_start', :to => "levels#set_start", :via => :get, :as => :set_start
    match '/save_start/:waypoint_id', :to => "levels#save_start", :via => :get, :as => :save_start
    match '/set_end', :to => "levels#set_end", :via => :get, :as => :set_end
    match '/save_end/:waypoints_id', :to => "levels#save_end", :via => :get, :as => :save_end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def levelSelect
    @levels = Level.all
  end

  def game
    @level = Level.find(params[:level])
    @start = Waypoint.find(@level.start)
    @end = Waypoint.find(@level.endd)
    @routes = Route.all
    @waypoints = []
    @routes.each do |r|
      @links = Link.where(rails_id: r.id )
      @wp = []

      @links.each do |l|
        @wp << Waypoint.find(l.wayspoint_id).id
      end

      @waypoints << Waypoint.where(id: @wp)
    end

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/game.html.erb
<script>
  <% for i in (0..(@routes.count-1)) %>
    var waypoints = [];
    <% @waypoints[i].each do |e|%>
      waypoints.push(new Waypoint("<%=e.name%>", new google.maps.LatLng(<%=e.lat%>, <%=e.lag%>), null));
    <% end %>
    var <%= @routes[i].name %> = new Route();
    <%= @routes[i].name %>.route = waypoints;
  <% end %>

  currentPosition = new Waypoint("<%=@start.name%>", new google.maps.LatLng(<%=@start.lat%>, <%=@start.lag%>), null);
  target = new Waypoint("<%=@end.name%>", new google.maps.LatLng(<%=@end.lat%>, <%=@end.lag%>), null);


  google.maps.event.addDomListener(window, 'load', initialize);

</script>

<div class="container">
  <div class="row">
      <div class="col-md-9">
        <div class="panel">
        <div class="map-container">
          <div id="map-canvas"></div>
        </div>
      </div>
      </div>

      <div class="col-md-3">
        <div class="panel panel-primary">
              <div class="panel-heading">Controls</div>
              <div class="panel-body">
                <% @routes.each do |route| %>
                 <button onclick="viewRoute(<%= route.name %>)" class="btn btn-primary btn-large">Show <%= route.name %> Route</button>
                <% end %>
                <button onclick="clearRoute()" class="btn btn-primary">Clear Route</button>
                <%= link_to "Reset", welcome_game_path, {class: "btn btn-danger"}%>
                <p> You currently at: <b id="currentPos"></b></p>
                <p> Your target is at: <b id="currentTarget"></b></p>
                <p> You currently have: Php <b id="currentFun"></b></p>
                <p id="errors"></p>
              </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
      <div class="jumbotron">
        <h3>Play Now1</h3>
        <%= link_to "Commuting for Dummies", welcome_select_path, {class: "btn btn-primary"} %>
        <br/>
        <%= link_to "Guess that Sign", grs_index_path, {class: "btn btn-primary"} %>
      </div>
  </div>
</div>

app/views/welcome/levelSelect.html.erb
<div align="center">

  <h2> Levels </h2>

  <p>
    <% @levels.each do |l| %>
    <%= l.start %>:<%= l.endd %>:<%= l.fare %><br/>
    <%= link_to "Play", welcome_game_path(l.id), {class: "btn btn-success"}%>
    <%end%>
  </p>

  <p>
    <%= link_to 'New Level', new_level_path %><br>
    <%= link_to 'New Waypoints', waypoints_path%><br>
    <%= link_to 'New Routes', routes_path %>
  </p>
</div>