config/routes.rb
Rails.application.routes.draw do
  resources :waypoints
  resources :routes do
  	match '/add_waypoints', :to => 'routes#add_waypoints', :via => :get, :as => :add_waypoints
  	match '/add_link/:waypoint_id', :to => 'routes#add_link', :via => :get, :as => :add_link
  end

  devise_for :users
  root 'welcome#index'
  get '/game/:level', :to => 'welcome#game', as: :welcome_game
  get '/levelSelect', :to => 'welcome#levelSelect', as: :welcome_select
  match "/guess_the_road_sign", :to => "guess_road_sign#index", :via => :get, :as => :grs_index
  match "/guess_the_road_sign/start", :to => "guess_road_sign#start", :via => :get, :as => :grs_start
  match "/guess_the_road_sign/:page", :to => "guess_road_sign#page", :via => :get, :as => :grs_page
  post "/guess_the_road_sign/:page/check", :to => "guess_road_sign#check", as: :grs_check

  resources :road_sign
  resources :levels do
    match '/set_start', :to => "levels#set_start", :via => :get, :as => :set_start
    match '/save_start/:waypoint_id', :to => "levels#save_start", :via => :get, :as => :save_start
    match '/set_end', :to => "levels#set_end", :via => :get, :as => :set_end
    match '/save_end/:waypoints_id', :to => "levels#save_end", :via => :get, :as => :save_end
  end
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_many :routes
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  def new
    @level = Level.new
  end

  def create
    @level  = Level.create(level_params)
    if @level.save
      redirect_to levels_path
    else
      render 'new'
    end
  end

  def show
    @level = Level.find(params[:id])
  end

  def set_start
    @level = Level.find(params[:level_id])
    @waypoints = Waypoint.all
  end

  def save_start
    @level = Level.find(params[:level_id])
    @level.update(start: params[:waypoint_id])
    redirect_to level_path(@level.id)
  end

  def set_end
    @level = Level.find(params[:level_id])
    @waypoints = Waypoint.all
  end

  def save_end
    @level = Level.find(params[:level_id])
    @level.update(endd: params[:waypoints_id])
    redirect_to level_path(@level.id)
  end

  def index
    @levels = Level.all
  end

  private
    def level_params
      params.require(:level).permit(:fare)
    end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/index.html.erb
<div align="center">

  <h2> Levels </h2>

  <p>
    <% @levels.each do |l| %>
      <%= l.start %>:<%= l.endd %>:<%= l.fare %>
      <%= link_to 'Show', level_path(l.id) %>
    <%end%> 
  </p>

  <p>
    <%= link_to 'New Level', new_level_path %>
  </p>
</div>

app/views/levels/new.html.erb
<div align="center">
<h2> New Level </h2>

  <div class="container">
  <%= form_for :level,  url: levels_path do |f| %>
    <p>
      <%= f.label :fare %>
      <%= f.text_field :fare %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <%end%>
  </div>

</div>

app/views/levels/set_end.html.erb
<div align="center">
  <h2> Available Waypoints </h2>

  <p>
  <% @waypoints.each do |w| %>
    <%= w.name %>
    <%= link_to 'Set', level_save_end_path(@level.id, w.id) %>
    <br>
  <% end %>
  </p>
</div>

app/views/levels/set_start.html.erb
<div align="center">
  <h2> Available Waypoints </h2>

  <p>
  <% @waypoints.each do |w| %>
    <%= w.name %>
    <%= link_to 'Set', level_save_start_path(@level.id, w.id) %>
    <br>
  <% end %>
  </p>
</div>

app/views/levels/show.html.erb
<div align="center">

  <p>
    <%= @level.start %>
    <%= link_to 'Set Start', level_set_start_path(@level.id) %>
  </p>
  <p>
    <%= @level.endd %>
    <%= link_to 'Set End', level_set_end_path(@level.id) %>
  </p>
  <p>
    <%= @level.fare %>
  </p>

</div>