config/routes.rb
Rails.application.routes.draw do
  resources :waypoints
  resources :routes do
  	match '/add_waypoints', :to => 'routes#add_waypoints', :via => :get, :as => :add_waypoints
  	match '/add_link/:waypoint_id', :to => 'routes#add_link', :via => :get, :as => :add_link
  end

  devise_for :users
  root 'welcome#index'
  get '/game/:level', :to => 'welcome#game', as: :welcome_game
  get '/levelSelect', :to => 'welcome#levelSelect', as: :welcome_select
  match "/guess_the_road_sign", :to => "guess_road_sign#index", :via => :get, :as => :grs_index
  match "/guess_the_road_sign/start", :to => "guess_road_sign#start", :via => :get, :as => :grs_start
  match "/guess_the_road_sign/:page", :to => "guess_road_sign#page", :via => :get, :as => :grs_page
  post "/guess_the_road_sign/:page/check", :to => "guess_road_sign#check", as: :grs_check

  resources :road_sign
  resources :levels do
    match '/set_start', :to => "levels#set_start", :via => :get, :as => :set_start
    match '/save_start/:waypoint_id', :to => "levels#save_start", :via => :get, :as => :save_start
    match '/set_end', :to => "levels#set_end", :via => :get, :as => :set_end
    match '/save_end/:waypoints_id', :to => "levels#save_end", :via => :get, :as => :save_end
  end
end

app/models/waypoint.rb
class Waypoint < ActiveRecord::Base
end

app/controllers/waypoint_controller.rb
class WaypointController < ApplicationController

	def create
	end
	
	def update
	end
	
	def store
		@waypoint = Waypoint.new waypoint_param
		if @waypoint.save
			redirect waypoint_index_path
		else
			render 'new'
		end
	end
	
	def index
		@waypoints = Waypoint.all
	end
	
	def new
		@waypoint = Waypoint.new
	end
	
	private
	
		def waypoint_param
			params.require(:waypoint).permit(:name, :lat, :lag)
		end
end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
  before_action :set_waypoint, only: [:show, :edit, :update, :destroy]

  # GET /waypoints
  # GET /waypoints.json
  def index
    @waypoints = Waypoint.all
  end

  # GET /waypoints/1
  # GET /waypoints/1.json
  def show
  end

  # GET /waypoints/new
  def new
    @waypoint = Waypoint.new
  end

  # GET /waypoints/1/edit
  def edit
  end

  # POST /waypoints
  # POST /waypoints.json
  def create
    @waypoint = Waypoint.new(waypoint_params)

    respond_to do |format|
      if @waypoint.save
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully created.' }
        format.json { render :show, status: :created, location: @waypoint }
      else
        format.html { render :new }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waypoints/1
  # PATCH/PUT /waypoints/1.json
  def update
    respond_to do |format|
      if @waypoint.update(waypoint_params)
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @waypoint }
      else
        format.html { render :edit }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waypoints/1
  # DELETE /waypoints/1.json
  def destroy
    @waypoint.destroy
    respond_to do |format|
      format.html { redirect_to waypoints_url, notice: 'Waypoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waypoint
      @waypoint = Waypoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waypoint_params
      params.require(:waypoint).permit(:name, :lat, :lat)
    end
end

app/helpers/waypoint_helper.rb
module WaypointHelper
end

app/helpers/waypoints_helper.rb
module WaypointsHelper
end

app/views/waypoints/_form.html.erb
<%= form_for(@waypoint) do |f| %>
  <% if @waypoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waypoint.errors.count, "error") %> prohibited this waypoint from being saved:</h2>

      <ul>
      <% @waypoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>  
  <br>
  <%= f.label :lat %>
  <%= f.text_field :lat %>  
  <br>
  <%= f.label :lag %>
  <%= f.text_field :lag %>  
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waypoints/edit.html.erb
<h1>Editing waypoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @waypoint %> |
<%= link_to 'Back', waypoints_path %>

app/views/waypoints/index.html.erb
<div class="container">

<h1>Listing waypoints</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waypoints.each do |waypoint| %>
      <tr>
      	<td><%= waypoint.name %></td>
        <td><%= link_to 'Show', waypoint_path(waypoint.id) %></td>
        <td><%= link_to 'Edit', edit_waypoint_path(waypoint) %></td>
        <td><%= link_to 'Destroy', waypoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waypoint', new_waypoint_path %>
</div>

app/views/waypoints/new.html.erb
<h1>New waypoint</h1>

<%= render 'form' %>

<%= link_to 'Back', waypoints_path %>

app/views/waypoints/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_waypoint_path(@waypoint) %> |
<%= link_to 'Back', waypoints_path %>