config/routes.rb
Rails.application.routes.draw do
  resources :waypoints
  resources :routes do
  	match '/add_waypoints', :to => 'routes#add_waypoints', :via => :get, :as => :add_waypoints
  	match '/add_link/:waypoint_id', :to => 'routes#add_link', :via => :get, :as => :add_link
  end

  devise_for :users
  root 'welcome#index'
  get '/game/:level', :to => 'welcome#game', as: :welcome_game
  get '/levelSelect', :to => 'welcome#levelSelect', as: :welcome_select
  match "/guess_the_road_sign", :to => "guess_road_sign#index", :via => :get, :as => :grs_index
  match "/guess_the_road_sign/start", :to => "guess_road_sign#start", :via => :get, :as => :grs_start
  match "/guess_the_road_sign/:page", :to => "guess_road_sign#page", :via => :get, :as => :grs_page
  post "/guess_the_road_sign/:page/check", :to => "guess_road_sign#check", as: :grs_check

  resources :road_sign
  resources :levels do
    match '/set_start', :to => "levels#set_start", :via => :get, :as => :set_start
    match '/save_start/:waypoint_id', :to => "levels#save_start", :via => :get, :as => :save_start
    match '/set_end', :to => "levels#set_end", :via => :get, :as => :set_end
    match '/save_end/:waypoints_id', :to => "levels#save_end", :via => :get, :as => :save_end
  end
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :links
end

app/models/routes.rb
class Routes < ActiveRecord::Base
  belongs_to :level
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  	@route = Route.find(params[:id])
  end
  
  def add_waypoints
  	@waypoints_list = Waypoint.all
  	@route = Route.find(params[:route_id])
  	@links = Link.where(rails_id: @route.id)
  	@wp = []
  	@idlist = []

  	@links.each do |l|
  		@wp << Waypoint.find(l.wayspoint_id).id
  	end
  	
  	@waypoints_list = Waypoint.where.not(id: @wp).all
    @waypoints_list2 = Waypoint.where(id: @wp).all
  end
  
  def add_link
  	@route = Route.find(params[:route_id])
  	@waypoint = Waypoint.find(params[:waypoint_id])
  	@link = Link.new
  	@link.update(rails_id: @route.id)
  	@link.update(wayspoint_id: @waypoint.id)
    redirect_to route_add_waypoints_path(@route.id)
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    #respond_to do |format|
      if @route.save
        #format.html { redirect_to @route, notice: 'Route was successfully created.' }
        #format.json { render :show, status: :created, location: @route }
        redirect_to routes_path
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:name)
    end
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f. label :name %>
  <%= f.text_field :name %>

  <div class="actions">
    <%= f.submit :submit, {class: "btn btn-success"}%>
  </div>
<% end %>

app/views/routes/add_waypoints.html.erb
<div class="container">

Available Waypoints
<br>
<% @waypoints_list.each do |w| %>
	<%= link_to w.name, route_add_link_path(@route.id, w.id) %><br>
	<%= w.lat %>, <%= w.lag %>
	<hr/>
<% end %>
Added Waypoints
<br>
<% @waypoints_list2.each do |w| %>
  <%= w.name %><br>
  <%= w.lat %>, <%= w.lag %>
	<hr/>

<% end %>
<br><br>
<%= link_to 'Back', routes_path %>

</div>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<div class="container">
  <h1>Available Routes</h1>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
      	<td><b><%= route.name %></b></td>
      	<td><%= link_to 'Show', route_path(route.id) %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Route', new_route_path , {class: "btn btn-default"}%>
</div>

app/views/routes/new.html.erb
<div class="container">

<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path , class: "btn btn-primary"%>

</div>

app/views/routes/show.html.erb
<div class="container">

<h1><%= @route.name %></h1>

<%= link_to 'Add Waypoint', route_add_waypoints_path(@route.id) %>

<div>